{
 "title": "Backup Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repository",
    "query": {
     "query": "label_values(borg_repository_info,repository)"
    }
   },
   {
    "name": "restic_repository",
    "query": {
     "query": "label_values(restic_last_snapshot_info,repository)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Borg summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "borg_total_size_bytes" },
    {
     "expr": "borg_deduplicated_compressed_size_bytes"
    },
    {
     "expr": "borg_last_backup_timestamp * 1000"
    },
    {
     "expr": "borg_last_backup_original_size_bytes"
    },
    {
     "expr": "borg_last_backup_compressed_size_bytes"
    },
    {
     "expr": "borg_last_backup_deduplicated_size_bytes"
    },
    { "expr": "borg_last_backup_files" },
    {
     "expr": "borg_last_backup_duration_seconds"
    },
    {
     "expr": "(time() * 1000) - (borg_last_backup_timestamp * 1000)"
    }
   ]
  },
  {
   "title": "Restic summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "restic_last_backup_timestamp * 1000"
    },
    {
     "expr": "restic_last_backup_original_size_bytes"
    },
    {
     "expr": "restic_last_backup_data_added_bytes"
    },
    { "expr": "restic_last_backup_files" },
    {
     "expr": "restic_last_backup_duration_seconds"
    },
    {
     "expr": "(time() * 1000) - (restic_last_backup_timestamp * 1000)"
    }
   ]
  },
  { "title": "Backups for $repository (Borg)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "repository" },
  {
   "title": "Last collection",
   "type": "stat",
   "description": "Time since last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(exporter_last_collect_timestamp{tool=\"borg\", repository=~\"^$repository$\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_last_collect_error{tool=\"borg\", repository=~\"^$repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection duration",
   "type": "stat",
   "description": "Duration of the last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_last_collect_duration_seconds{tool=\"borg\", repository=~\"^$repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archive history",
   "type": "table",
   "description": "Size, file count and duration for the last N archives of this repository (see ARCHIVE_HISTORY_LIMIT), including archives that predate the exporter tracking this repository.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_duration_seconds{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_files{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_original_size_bytes{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_compressed_size_bytes{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_deduplicated_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive files",
   "type": "barchart",
   "description": "Number of files for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_files{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive duration",
   "type": "barchart",
   "description": "Backup duration for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_duration_seconds{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive original size",
   "type": "barchart",
   "description": "Original size for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_original_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive compressed size",
   "type": "barchart",
   "description": "Compressed size for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_compressed_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive unique data added",
   "type": "barchart",
   "description": "New data each archive added to the repository, relative to what else is currently in the repository (not the same as the archive's own size). Recomputed each collection, so older bars can change as newer archives are added.",
   "gridPos": { "h": 8, "w": 4.8, "x": 14.4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_deduplicated_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Backups for $restic_repository (Restic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "repeat": "restic_repository"
  },
  {
   "title": "Archive history",
   "type": "table",
   "description": "Size, file count and duration for the last N snapshots of this repository (see ARCHIVE_HISTORY_LIMIT). Duration and Unique Data Added are unset for snapshots taken by a restic version too old to record them.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "restic_archive_timestamp{repository=~\"^$restic_repository$\"} * 1000"
    },
    {
     "expr": "restic_archive_duration_seconds{repository=~\"^$restic_repository$\"}"
    },
    {
     "expr": "restic_archive_files{repository=~\"^$restic_repository$\"}"
    },
    {
     "expr": "restic_archive_original_size_bytes{repository=~\"^$restic_repository$\"}"
    },
    {
     "expr": "restic_archive_data_added_bytes{repository=~\"^$restic_repository$\"}"
    }
   ]
  },
  {
   "title": "Archive files",
   "type": "barchart",
   "description": "Number of files for the last N snapshots of this repository.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "restic_archive_timestamp{repository=~\"^$restic_repository$\"} * 1000"
    },
    {
     "expr": "restic_archive_files{repository=~\"^$restic_repository$\"}"
    }
   ]
  },
  {
   "title": "Archive duration",
   "type": "barchart",
   "description": "Backup duration for the last N snapshots of this repository. Unset for snapshots taken by a restic version too old to record it.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "restic_archive_timestamp{repository=~\"^$restic_repository$\"} * 1000"
    },
    {
     "expr": "restic_archive_duration_seconds{repository=~\"^$restic_repository$\"}"
    }
   ]
  },
  {
   "title": "Archive original size",
   "type": "barchart",
   "description": "Original size for the last N snapshots of this repository.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "restic_archive_timestamp{repository=~\"^$restic_repository$\"} * 1000"
    },
    {
     "expr": "restic_archive_original_size_bytes{repository=~\"^$restic_repository$\"}"
    }
   ]
  },
  {
   "title": "Archive unique data added",
   "type": "barchart",
   "description": "New data each snapshot added to the repository (restic's snapshot summary 'data_added'). Unset for snapshots taken by a restic version too old to record it.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "restic_archive_timestamp{repository=~\"^$restic_repository$\"} * 1000"
    },
    {
     "expr": "restic_archive_data_added_bytes{repository=~\"^$restic_repository$\"}"
    }
   ]
  },
  {
   "title": "Last collection",
   "type": "stat",
   "description": "Time since last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(exporter_last_collect_timestamp{tool=\"restic\", repository=~\"^$restic_repository$\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 67 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_last_collect_error{tool=\"restic\", repository=~\"^$restic_repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection duration",
   "type": "stat",
   "description": "Duration of the last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_last_collect_duration_seconds{tool=\"restic\", repository=~\"^$restic_repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}