{
 "title": "Borg",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "repository",
    "query": {
     "query": "label_values(borg_repository_info,repository)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "borg_total_size_bytes" },
    {
     "expr": "borg_deduplicated_compressed_size_bytes"
    },
    {
     "expr": "borg_last_backup_timestamp * 1000"
    },
    {
     "expr": "borg_last_backup_original_size_bytes"
    },
    {
     "expr": "borg_last_backup_compressed_size_bytes"
    },
    {
     "expr": "borg_last_backup_deduplicated_size_bytes"
    },
    { "expr": "borg_last_backup_files" },
    {
     "expr": "borg_last_backup_duration_seconds"
    },
    {
     "expr": "(time() * 1000) - (borg_last_backup_timestamp * 1000)"
    }
   ]
  },
  { "title": "Backups for $repository", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "repository" },
  {
   "title": "Last collection",
   "type": "stat",
   "description": "Time since last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - last_over_time(borg_last_collect_timestamp{repository=~\"^$repository$\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection error",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_last_collect_error{repository=~\"^$repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last collection duration",
   "type": "stat",
   "description": "Duration of the last exporter collection",
   "gridPos": { "h": 9, "w": 2, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "borg_last_collect_duration_seconds{repository=~\"^$repository$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archive history",
   "type": "table",
   "description": "Size, file count and duration for the last N archives of this repository (see ARCHIVE_HISTORY_LIMIT), including archives that predate the exporter tracking this repository.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_duration_seconds{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_files{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_original_size_bytes{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_compressed_size_bytes{repository=~\"^$repository$\"}"
    },
    {
     "expr": "borg_archive_deduplicated_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive files",
   "type": "barchart",
   "description": "Number of files for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_files{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive duration",
   "type": "barchart",
   "description": "Backup duration for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 4.8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_duration_seconds{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive original size",
   "type": "barchart",
   "description": "Original size for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 9.6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_original_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive compressed size",
   "type": "barchart",
   "description": "Compressed size for the last N archives of this repository.",
   "gridPos": { "h": 8, "w": 4.8, "x": 14.4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_compressed_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  },
  {
   "title": "Archive unique data added",
   "type": "barchart",
   "description": "New data each archive added to the repository, relative to what else is currently in the repository (not the same as the archive's own size). Recomputed each collection, so older bars can change as newer archives are added.",
   "gridPos": { "h": 8, "w": 4.8, "x": 19.2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "borg_archive_timestamp{repository=~\"^$repository$\"} * 1000"
    },
    {
     "expr": "borg_archive_deduplicated_size_bytes{repository=~\"^$repository$\"}"
    }
   ]
  }
 ]
}